# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19e646bcf0763e7751433c7dbe3f69461d1afbd177d6cdeedfd5e0ca7314bd1864e9906216d807ccf25326c8b2aa1e001202ccf4eec67b5b2d6e4840a48b9387

test:
  secret_key_base: 66670302cf2d80fc1637d22305bb16cebb774ac47b5b560cfd52d1a302604993f32b6d793ce277d3a97c1882149c9a46e1b2fd0397e69a20c80493f830254651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
